### ISSUE TITLE
[Question] Is it possible to use org-formation without owning the master account?

### ISSUE THREAD

**Issue by cwyl02** [OlafConijn/AwsOrganizationFormation#28]
Hi org-formation maintainer(s), 

Recently we have been looking at Control Tower and decided to back out because our accounts will probably roll under some vendor's OU to get some discounts and such. 

In that kind of set up, are we still able to use org-formation?  From a quick look at the features.pdf and the readmes, seems like the answer is no - we have to own the master account to use org-formation. But would still like to check with you to make sure I understand things correctly.

Thank you in advance!
York

**Comment by OlafConijn** [comment]
Hi York,

in order to use organization formation, especially the part where you create accounts, ou's and other organization level resources you will indeed need access to the master account. Owning and having access is technically not the same thing - but i think this is how i interpret your question.

I also think that it is an interesting usecase to run commands like `update-stacks` in the context of an account that is not the master account. Technically executing CloudFormation in multiple accounts still is possible as long as you are able to assume a role in the other accounts. This would even work if the accounts are not part of the same AWS organization or owned by different companies - like in the scenario where you manage software in the AWS accounts of various customers, e.g.

i think the above would definitely be interesting to look at - at least understand the impact and design - if this indeed is what you are after. 

What i could do if this helps is create a list of permissions that you need to run various aspects of org-formation if that helps.

take care!
Olaf

**Comment by cwyl02** [comment]
Hi Olaf,

Thanks for you quick and thorough response!

You actually brought up a good point about owning vs. accessing the account. After more readings, I actually found that the use case above is actually kind of meaningless because it is not centralized control of sub accounts, which is one of the main reasons to use AWS Org at all. 

Now let's say, we are going to spin up a bunch of these new sub accounts, join vendor's AWS Org, without using org-formation/any tools. Then one day, I would like to leave the vendor's AWS Org and I will create and own a new master account X -- full access, billing responsibility and etc. At that time, is it possible to "import" the existing sub accounts into the new master account X?

York

**Comment by OlafConijn** [comment]
hi!

yes, it is possible to have an account leave and then join another organization. As you just implied the master account is (typically) the account that gets billed and (typically) has full access to any account in its organization. 

The process is tedious because there will be a moment in time in which the account does not belong to any AWS Organization. Therefore you need to redo all the billing details (e.g. credit card) of the account.

AWS documentation on
- Join: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_invites.html
- Leave: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_remove.html

the cool thing about my tool (haha ;)) - you can re init the organization file at any step using `org-formation init` and have changes to your organization reflected in the IaC file. 

Unfortunately it is not possible to join/leave/delete using the tool, simple because AWS doesn't provide an API for this. you apparantly can use the internal (unsupported) api's that the console uses (https://github.com/sentialabs/coto) but i would not recommend it

**Comment by cwyl02** [comment]
It is totally manageable if the Join/Leave are the only manual steps needed when change of AWS Org structure happen. org-formation is indeed cool in this sense! Again, thank you Olaf!!
